### ISSUE TITLE
byte-array not available in clojurescript

### ISSUE THREAD

**Issue by lambda-ai** [replikativ/hasch#5]
Hi,

I'm getting clojurescript compiler warnings after adding hasch as a dependency. The reason seems to be that byte-array isn't available in clojurescript while it's used here: https://github.com/replikativ/hasch/blob/7d5654a30c90dff8e2ad4bcf4cf8c69af7e67d6a/src/hasch/core.cljc#L58

It's no big deal, since I'm not using the b64-hash function anyway, and it's only a warning. But still it's annoying, and I'm having some figwheel reload troubles that I'm not completely sure are unrelated.

Thanks,
-Mathias

**Comment by whilo** [comment]
Thanks for pointing it out and sorry for the inconvenience. Should be fixed in current master now and I have pushed a 0.3.6-SNAPSHOT release.

**Comment by lambda-ai** [comment]
thanks for the super-fast response!
